@startuml
class User {
  String id
  List ownedStuff 
}

class Stuff {
  String id
}

class Locker {
  String id
  List containedStuff
}
User - Stuff : owns
User *- Stuff : offers for rent
User -- Stuff : rents

Stuff - Locker : contains

@enduml
